service: mongoose-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 128
  timeout: 30
  environment:
    MONGO_URI: $(env.MONGO_URI)

package:
  exclude:
    - .git/**
    - .gitignore
    - __tests__/**
    - README.md
    - jest.config.cjs
    - .github/**
    - eslint.config.mjs
    - tsconfig.json
    - .build/**
    - index.ts
    - node_modules/** 


functions:
  api:
    handler: dist/index.handler
    url:  
      authType: NONE  
      cors: true
    events:
      - http:
          path: /
          method: get
          cors: true  # Enables CORS
      - http:
          path: fetchHosts
          method: get
          cors: true
      - http:
          path: fetchHosts/{state}
          method: get
          cors: true
      - http:
          path: fetchHost/{id}
          method: get
          cors: true
      - http:
          path: insert_review
          method: post
          cors: true


plugins:
- serverless-dotenv-plugin
- serverless-prune-plugin

  
custom:
  prune:
    automatic: true  
    number: 1 